app:
  blockTarget: "127.0.0.1"
  state: "state.json"

# os:
#   macos: "/etc/hosts"
#   linux: "/etc/hosts"
#   windows: "/etc/hosts"

# whitelist:
#   - somesite
#
blacklist:
  - facebook.com
  - ynet.co.il
  - instagram.com
  - twitter.com
  - linkedin.com
