app:
  blockTarget: "127.0.0.1"
  state: "state.json"

blacklist:
  - www.facebook.com
  - www.ynet.co.il
  - www.instagram.com
  - www.twitter.com

whitelist:
  - somesite

os:
  macos: "/etc/hosts"
  linux: "/etc/hosts"
  windows: "/etc/hosts"


